# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-07 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeiboUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weibo_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('weibo_name', models.CharField(blank=True, max_length=40, null=True, verbose_name=b'weibo name')),
                ('gender', models.CharField(choices=[(b'm', b'Male'), (b'f', b'Female')], max_length=1)),
                ('province', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('city', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'weibo user',
                'verbose_name_plural': 'weibo users',
            },
        ),
    ]
